### ISSUE TITLE
Can't seem to get shortcuts working

### ISSUE THREAD

**Issue by mooror** [matsumos/grunt-slim#12]
Can you guys please tell me how i might be able to use shortcuts in grunt-slim. I thought that perhaps you would add a "shortcuts:," section to the options array but that didnt seem to work as i got errors about an unexpected equal sign. Heres my code:

options: {                       // Target options
                    pretty:true,
                    shortcut:{'art' => {:tag => 'article'}, '#' => {:attr => 'id'}, '.' => {:attr => 'class'} }
                  }

And Here is the error:
ERROR

> > SyntaxError: /home/mooror/Documents/Aptana Studio 3 Workspace/One Way Media Html 5/Gruntfile.js:32
> >                              shortcut:{'art' => {:tag => 'article'}, '#' => {:attr => 'id'}, '.'
> >                                              ^
> > Unexpected token =

Thank you for any help you can offer,
Mooror

**Comment by cognitom** [comment]
Use JavaScript.

``` javascript
options: { // Target options
  pretty:true,
  shortcut: { 'art': { tag: 'article' }, '#': { attr: 'id' }, '.': { attr: 'class' } }
}
```
