### ISSUE TITLE
Glob support?

### ISSUE THREAD

**Issue by mrjoelkemp** [matsumos/grunt-slim#2]
Is there glob support for compiling multiple files into separate files? In other words, is there support for something similar to:

_Taken from [grunt-contrib-coffee](https://github.com/gruntjs/grunt-contrib-coffee#usage-examples)_

```
  glob_to_multiple: {
    cwd: 'path/to',
    src: ['*.coffee'],
    dest: 'path/to/dest/'
  }
```

I've tried doing this with glob syntax in the `files` object definition of the task and I get a folder created with the name `**`.

Thanks!

**Comment by anshul** [comment]
I need this too...

**Comment by matsumos** [comment]
Try expand:true

``` javascript
slim: {
  compile: {
    files: [{
      expand: true
      cwd: 'path/to'
      src: ['{,*/}*.slim']
      dest: 'path/to/dest'
      ext: '.html'
    }]
  }
}
```

**Comment by mrjoelkemp** [comment]
:+1:  Thanks a ton!
