### ISSUE TITLE
compile process is very slow

### ISSUE THREAD

**Issue by d6u** [matsumos/grunt-slim#5]
My gruntfile setting:

```
slim:
  angular_templates:
    files: [{
      expand: true
      cwd:  '<%= compileSettings["html"]["source folder"] %>'
      src:  '**/*.slim'
      dest: '<%= compileSettings["html"]["target folder"] %>'
      ext:  '.html'
    }]
```

It usually take 10s to compile 10 templates, compare to Jade's about 2s. Do you happen to know the reason?

Thank you in advance.

**Comment by Fire-Dragon-DoL** [comment]
@daiweilu this is probably related to slim itself, not grunt-slim
